"""커뮤니티_게시글_테이블_추가

Revision ID: 01eb4c6703e1
Revises: ab84be844747
Create Date: 2025-12-18 20:56:26.075252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01eb4c6703e1'
down_revision: Union[str, Sequence[str], None] = 'ab84be844747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('general', 'request', name='communityposttype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('request_category', sa.String(length=100), nullable=True),
    sa.Column('desired_start_date', sa.Date(), nullable=True),
    sa.Column('desired_end_date', sa.Date(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_posts_club_id'), 'community_posts', ['club_id'], unique=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_index(op.f('ix_community_posts_request_category'), 'community_posts', ['request_category'], unique=False)
    op.create_index(op.f('ix_community_posts_tags'), 'community_posts', ['tags'], unique=False)
    op.create_index(op.f('ix_community_posts_title'), 'community_posts', ['title'], unique=False)
    op.create_index(op.f('ix_community_posts_type'), 'community_posts', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_posts_type'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_title'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_tags'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_request_category'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_club_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.drop_table('community_posts')
    # ### end Alembic commands ###
