"""물품관리 인벤토리 테이블 추가

Revision ID: 3a25de9631d6
Revises: 75b17e3dc042
Create Date: 2025-12-15 09:08:08.500001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a25de9631d6'
down_revision: Union[str, Sequence[str], None] = '75b17e3dc042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_admins',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('club_id', 'user_id'),
    sa.UniqueConstraint('club_id', 'user_id', name='uq_club_admins_club_user')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=80), nullable=True),
    sa.Column('contact', sa.String(length=120), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'RENTED', 'SOLD', 'UNAVAILABLE', name='itemstatus'), nullable=False),
    sa.Column('is_deal_done', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_items_club_id'), 'inventory_items', ['club_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_is_deal_done'), 'inventory_items', ['is_deal_done'], unique=False)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_items_status'), 'inventory_items', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_items_tags'), 'inventory_items', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_tags'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_status'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_is_deal_done'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_club_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('club_admins')
    # ### end Alembic commands ###
