"""학교·동아리 및 관리자 매핑 테이블 추가

Revision ID: 75b17e3dc042
Revises: 
Create Date: 2025-12-15 06:14:05.172931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '75b17e3dc042'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=False)
    op.create_index(op.f('ix_clubs_school_id'), 'clubs', ['school_id'], unique=False)
    op.drop_index(op.f('ix_test_items_id'), table_name='test_items')
    op.drop_index(op.f('ix_test_items_name'), table_name='test_items')
    op.drop_table('test_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_test_items_name'), 'test_items', ['name'], unique=False)
    op.create_index(op.f('ix_test_items_id'), 'test_items', ['id'], unique=False)
    op.drop_index(op.f('ix_clubs_school_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
