"""거래 listing 및 예약 테이블 추가

Revision ID: ab84be844747
Revises: 3a25de9631d6
Create Date: 2025-12-15 09:33:40.084053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab84be844747'
down_revision: Union[str, Sequence[str], None] = '3a25de9631d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trade_type', sa.Enum('RENT', 'SELL', name='tradetype'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_listings_inventory_item_id'), 'trade_listings', ['inventory_item_id'], unique=True)
    op.create_index(op.f('ix_trade_listings_is_public'), 'trade_listings', ['is_public'], unique=False)
    op.create_index(op.f('ix_trade_listings_trade_type'), 'trade_listings', ['trade_type'], unique=False)
    op.create_table('trade_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.Enum('RENT', 'SELL', name='tradetype'), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELED', name='reservationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['trade_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_reservations_listing_id'), 'trade_reservations', ['listing_id'], unique=False)
    op.create_index(op.f('ix_trade_reservations_status'), 'trade_reservations', ['status'], unique=False)
    op.create_index(op.f('ix_trade_reservations_trade_type'), 'trade_reservations', ['trade_type'], unique=False)
    op.create_index(op.f('ix_trade_reservations_user_id'), 'trade_reservations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # MySQL에서는 FK에 필요한 인덱스를 먼저 drop하려 하면 실패할 수 있음.
    # 테이블을 먼저 drop하면 FK/인덱스가 함께 제거되므로 가장 안전하다.
    op.drop_table("trade_reservations")

    # 부모 테이블(리스트) 제거
    op.drop_table("trade_listings")