"""공연_테이블_추가

Revision ID: cc64c5e54795
Revises: 01eb4c6703e1
Create Date: 2025-12-19 06:52:34.353559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc64c5e54795'
down_revision: Union[str, Sequence[str], None] = '01eb4c6703e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('theme_category', sa.String(length=100), nullable=False),
    sa.Column('poster_image_url', sa.String(length=500), nullable=True),
    sa.Column('performance_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performances_club_id'), 'performances', ['club_id'], unique=False)
    op.create_index(op.f('ix_performances_id'), 'performances', ['id'], unique=False)
    op.create_index(op.f('ix_performances_performance_date'), 'performances', ['performance_date'], unique=False)
    op.create_index(op.f('ix_performances_region'), 'performances', ['region'], unique=False)
    op.create_index(op.f('ix_performances_school_id'), 'performances', ['school_id'], unique=False)
    op.create_index(op.f('ix_performances_theme_category'), 'performances', ['theme_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performances_theme_category'), table_name='performances')
    op.drop_index(op.f('ix_performances_school_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_region'), table_name='performances')
    op.drop_index(op.f('ix_performances_performance_date'), table_name='performances')
    op.drop_index(op.f('ix_performances_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_club_id'), table_name='performances')
    op.drop_table('performances')
    # ### end Alembic commands ###
